export const MAJORS: string[] = [
  // Business & Management
  'Business Administration',
  'Business Management',
  'International Business Management',
  'Marketing Management',
  'Digital Marketing',
  'Media Marketing',
  'Services Management',
  'Tourism Management',
  'Hospitality Management',
  'Events Management',
  'Aviation Management',
  'Banking & Finance',
  'Islamic Banking & Finance',
  // Accounting
  'Accounting',
  'Forensic Accounting',
  // Computing & IT
  'Information & Communication Technology (ICT)',
  'Information Technology',
  'Computer Science',
  'Software Engineering',
  'Artificial Intelligence',
  'Data Science',
  'Data Analytics',
  'Cyber Security',
  'Digital Forensics',
  'Cloud Engineering',
  'FinTech',
  'Business Information Systems',
  'Sustainable Computing',
  'Information Systems Security',
  'Interactive Media',
  'Immersive Technology (VR/AR)',
  'Computer Games Development',
  'Web Media Technology',
  'Enterprise Computing',
  'Media Informatics',
  'Technopreneurship',
  // Engineering
  'Computer Engineering',
  'Electronic Engineering',
  'Electronic Engineering with IT',
  'Mechatronic Engineering',
  'Electrical & Electronic Engineering',
  'Telecommunication Engineering',
  'Petroleum Engineering',
  'Mechanical Engineering',
  // Design, Media & Arts
  'Industrial Design',
  'Visual Effects',
  'Animation',
  'Digital Advertising',
  'Media & Communication Studies',
  // Social Sciences
  'International Relations',
  'Psychology',
  // Fallback
  'Other',
];
